### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by grandebiengrande** [0xf15/tiktok#1]
The checker doesn't work, probably got patched
In print(res) it prints a blank response and when it prints the attempts it keeps printing [/] Attempts: 0 | R/S: 0
![image](https://github.com/0xf15/tiktok/assets/82174258/14cb6952-5e45-43ce-96de-4754af0d5dd9)

**Comment by 0xf15** [comment]
Chnger User-agent to Your FirFox And Add New Session id web
